name: 'Build Release'
description: 'Build release binary with optional cross-compilation'
inputs:
  target:
    description: 'Target triple for cross-compilation'
    required: false
    default: ''
  use-cross:
    description: 'Use cross for cross-compilation'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install cross
      if: inputs.use-cross == 'true'
      shell: bash
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build with cargo
      if: inputs.use-cross == 'false'
      shell: bash
      run: |
        if [ -n "${{ inputs.target }}" ]; then
          cargo build --release --target ${{ inputs.target }}
        else
          cargo build --release
        fi

    - name: Build with cross
      if: inputs.use-cross == 'true'
      shell: bash
      run: cross build --release --target ${{ inputs.target }}
