name: 'Build Release'
description: 'Build release binary with optional cross-compilation'
inputs:
  target:
    description: 'Target triple for cross-compilation'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Build with cargo
      shell: bash
      run: |
        if [ -n "${{ inputs.target }}" ]; then
          cargo build --release --target ${{ inputs.target }}
        else
          cargo build --release
        fi
