[package]
name = "picolayer"
version = "0.1.0"
edition = "2021"
authors = ["Picolayer Contributors"]
description = "Ensures minimal container layers - A Rust clone of nanolayer"
license = "MIT"
repository = "https://github.com/skevetter/picolayer"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tempfile = "3.8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
flate2 = "1.0"
tar = "0.4"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
