name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Check binary size
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            SIZE=$(stat -f%z "target/release/picolayer")
          else
            SIZE=$(stat -c%s "target/release/picolayer")
          fi

          MB_SIZE=$((SIZE / 1024 / 1024))
          echo "Binary size: $MB_SIZE MB"
          if [ "$SIZE" -gt 20000000 ]; then
            echo "Warning: Binary size exceeds 20MB"
            exit 1
          fi
